export { default as HomePage } from './HomePage/HomePage.jsx'
export { default as AboutPage } from './AboutPage/AboutPage.jsx'
export { default as PartnersPage } from './PartnersPage/PartnersPage.jsx'
export { default as ServicesPage } from './ServicesPage/ServicesPage.jsx'
export { default as SingleServicePage } from './SingleServicePage/SingleServicePage.jsx'