export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Navbar } from '../containers/navbar/Navbar'
export { default as Partners } from './partners/Partners'
export { default as Services } from './services/Services'
export { default as WhyUs } from './whyUs/WhyUs'